json.id blog_posts.id 
json.title blog_posts.title
json.url blog_posts.url
json.subtitle blog_posts.subtitle
json.description blog_posts.description
json.blog blog_posts.data.url
json.thumb blog_posts.data.url(:thumb)
json.created_at blog_posts.created_at
json.type blog_posts.content_type