defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  database: diabee_development
  <<: *defaults

test:
  database: diabee_test
  <<: *defaults

production:
  database: diabee_production
  <<: *defaults